### PR TITLE
Bump version to 1.14

### PR DESCRIPTION
**Pull request by irvifa**
Bumping the version to 1.14

### CODE REVIEW

**Comment by yue9944882** [comment]
thank you for reviving this! can you have a re-run w/ the latest generator, there's a few expected fixes:

```bash
OPENAPI_GENERATOR_COMMIT=v4.1.0 <the-gen-repo>/perl.sh
```

**Comment by irvifa** [comment]
@yue9944882 I already do as you asked. Thank you..
By the way I realize that we have no makefile and yet travis is running test and thus the test is failing.

**Pull request closed without merging**
